Prime permutation
---

1487, 4817, 8147 each increase by 3330, are all prime, and are all permutations of another. What's the other like this?

In [8]:
import sympy as sp
import numpy as np

In [6]:
p4d = list(sp.primerange(1000,10000))

In [7]:
len(p4d)

1061

In [14]:
diffs = np.array([ [abs(thing1 - thing2) for thing1 in p4d] for thing2 in p4d])

In [15]:
diffs

array([[   0,    4,   10, ..., 8940, 8958, 8964],
       [   4,    0,    6, ..., 8936, 8954, 8960],
       [  10,    6,    0, ..., 8930, 8948, 8954],
       ...,
       [8940, 8936, 8930, ...,    0,   18,   24],
       [8958, 8954, 8948, ...,   18,    0,    6],
       [8964, 8960, 8954, ...,   24,    6,    0]])

In [18]:
np.unique(diffs, return_counts=True)

(array([   0,    2,    4, ..., 8958, 8960, 8964]),
 array([1061,  340,  324, ...,    2,    2,    2], dtype=int64))